# Generated by Django 4.1.3 on 2022-11-30 13:07

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_service_delete_contract_alter_about_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='content_en',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='content_ru',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='content_uz',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='title_en',
            field=models.CharField(max_length=220, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='title_ru',
            field=models.CharField(max_length=220, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='title_uz',
            field=models.CharField(max_length=220, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='content_en',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='content_ru',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='content_uz',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='name_en',
            field=models.CharField(max_length=220, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='name_ru',
            field=models.CharField(max_length=220, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='name_uz',
            field=models.CharField(max_length=220, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='service_en',
            field=models.CharField(max_length=220, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='service_ru',
            field=models.CharField(max_length=220, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='service_uz',
            field=models.CharField(max_length=220, null=True),
        ),
    ]
