# Generated by Django 4.1.3 on 2022-11-26 08:18

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_alter_contactus_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='phone',
            field=phone_field.models.PhoneField(blank=True, max_length=31),
        ),
    ]
