# Generated by Django 4.1.3 on 2022-12-01 09:09

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='static/image')),
                ('title', models.CharField(max_length=220)),
                ('title_uz', models.CharField(max_length=220, null=True)),
                ('title_ru', models.CharField(max_length=220, null=True)),
                ('title_en', models.CharField(max_length=220, null=True)),
                ('content', ckeditor.fields.RichTextField()),
                ('content_uz', ckeditor.fields.RichTextField(null=True)),
                ('content_ru', ckeditor.fields.RichTextField(null=True)),
                ('content_en', ckeditor.fields.RichTextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_published', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='static/images')),
                ('title', models.CharField(max_length=220)),
                ('title_uz', models.CharField(max_length=220, null=True)),
                ('title_ru', models.CharField(max_length=220, null=True)),
                ('title_en', models.CharField(max_length=220, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_published', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Reason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220)),
                ('title_uz', models.CharField(max_length=220, null=True)),
                ('title_ru', models.CharField(max_length=220, null=True)),
                ('title_en', models.CharField(max_length=220, null=True)),
                ('content', ckeditor.fields.RichTextField()),
                ('content_uz', ckeditor.fields.RichTextField(null=True)),
                ('content_ru', ckeditor.fields.RichTextField(null=True)),
                ('content_en', ckeditor.fields.RichTextField(null=True)),
                ('icon', models.ImageField(upload_to='static/images')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_published', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ReasonImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='static/images')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_published', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ReasonTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220)),
                ('title_uz', models.CharField(max_length=220, null=True)),
                ('title_ru', models.CharField(max_length=220, null=True)),
                ('title_en', models.CharField(max_length=220, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_published', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='static/images')),
                ('title', models.CharField(max_length=220)),
                ('title_uz', models.CharField(max_length=220, null=True)),
                ('title_ru', models.CharField(max_length=220, null=True)),
                ('title_en', models.CharField(max_length=220, null=True)),
                ('content', ckeditor.fields.RichTextField()),
                ('content_uz', ckeditor.fields.RichTextField(null=True)),
                ('content_ru', ckeditor.fields.RichTextField(null=True)),
                ('content_en', ckeditor.fields.RichTextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_published', models.BooleanField(default=False)),
            ],
        ),
    ]
