# Generated by Django 4.1.3 on 2022-12-02 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Navbar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=220)),
                ('name_uz', models.CharField(max_length=220, null=True)),
                ('name_ru', models.CharField(max_length=220, null=True)),
                ('name_en', models.CharField(max_length=220, null=True)),
                ('link', models.CharField(max_length=220)),
            ],
        ),
    ]
